# This is a basic workflow to help you get started with Actions
# With thanks to https://github.com/BiscuitUmU/FantasyPlayer/blob/testing/.github/workflows/release.yml

name: WondrousTailsCopier Release

# Controls when the action will run. Triggers the workflow on tag creation
on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          tag_prefix: v
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet Packages
        run: nuget restore WondrousTailsCopier.sln

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://github.com/goatcorp/dalamud-distrib/raw/refs/heads/main/api11/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
        
      - name: Build
        run: msbuild WondrousTailsCopier.sln /p:Configuration=Release /property:Version=${{ steps.tag_version.outputs.new_version }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Wondrous Tails Copier - ${{ steps.tag_version.outputs.new_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./WondrousTailsCopier/bin/x64/Release/WondrousTailsCopier/latest.zip
          asset_name: latest.zip
          asset_content_type: application/zip 

      - name: Rollback Release
        if: ${{ failure() }}
        uses: liudonghua123/delete-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Wondrous Tails Copier - ${{ steps.tag_version.outputs.new_tag }}

      - name: Repository Dispatch
        if: ${{ success() }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: zettiverse/DalamudRepo
          event-type: plugin-updated
          client-payload: '{"repo_name": "${{ github.event.repository.name }}", "version": "${{ steps.tag_version.outputs.new_version }}"}'
